### ISSUE TITLE
Simplify association controller development for Doctrine entities.

### ISSUE THREAD

**Issue by kherge** [kherge-php/resource-bundle#2]
## Problem

Currently, only an abstract association controller is available. This requires that developers create their own classes to support resource association management. While this is understandable for manually registered resources, it makes less sense for Doctrine entity resources since how resources associations are managed is known quantity.

## Resolution

Create an association controller specifically for supporting Doctrine entity resource associations. It should be possible to reduce the complexity down to a simple map of entity association fields to entity resource class names. Something like the following could be used to create a new controller to manage resource associations for an individual entity resource:

```yaml
services:

    my_example.resource.manufacturer_cars_controller:
        parent: kherge_resource.association_controller
        calls:
            - 'setAssociations'
            - [{ car: "MyExample:Car" }]
```
